"""empty message

Revision ID: 0b69d6adaf63
Revises: 2113a4748683
Create Date: 2017-11-10 13:56:37.964705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b69d6adaf63'
down_revision = '2113a4748683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('progress_note', sa.Text(length=200000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'progress_note')
    # ### end Alembic commands ###
