"""empty message

Revision ID: 0e50c20e6985
Revises: e95dc53eca8a
Create Date: 2017-10-06 16:17:32.731952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e50c20e6985'
down_revision = 'e95dc53eca8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'project_id')
    # ### end Alembic commands ###
