"""empty message

Revision ID: 2113a4748683
Revises: 7972ed00f16e
Create Date: 2017-11-07 13:31:11.495204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2113a4748683'
down_revision = '7972ed00f16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_phase', sa.String(length=200), nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'project_phase')
    # ### end Alembic commands ###
