"""debug test5

Revision ID: 345dc3da558c
Revises: 894f42faaa79
Create Date: 2017-10-10 14:52:33.083181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '345dc3da558c'
down_revision = '894f42faaa79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'department_id',
               existing_type=mysql.INTEGER(display_width=11))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
