"""empty message

Revision ID: 409f4c1fe1a5
Revises: d745f4d7f157
Create Date: 2017-10-12 12:30:13.767772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409f4c1fe1a5'
down_revision = 'd745f4d7f157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subs', sa.Column('id', sa.Integer(), nullable=False))
    op.create_unique_constraint('member_project_id', 'subs', ['project_id', 'member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('member_project_id', 'subs', type_='unique')
    op.drop_column('subs', 'id')
    # ### end Alembic commands ###
