"""empty message

Revision ID: 75c8566c5c09
Revises: 345dc3da558c
Create Date: 2017-10-10 16:00:40.198070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c8566c5c09'
down_revision = '345dc3da558c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'employees', ['project_lead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'project_lead_id')
    # ### end Alembic commands ###
