"""debug test1

Revision ID: 894f42faaa79
Revises: f8f56a7bfeba
Create Date: 2017-10-10 12:54:24.973541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894f42faaa79'
down_revision = 'f8f56a7bfeba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'department_id')
    # ### end Alembic commands ###
