"""empty message

Revision ID: c42ddf307dd9
Revises: 02a836901650
Create Date: 2017-10-26 12:39:31.750950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42ddf307dd9'
down_revision = '02a836901650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
