"""empty message

Revision ID: d745f4d7f157
Revises: c65dc8b7626c
Create Date: 2017-10-12 12:20:43.882381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd745f4d7f157'
down_revision = 'c65dc8b7626c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'subs_ibfk_1', 'subs', type_='foreignkey')
    op.drop_constraint(u'subs_ibfk_2', 'subs', type_='foreignkey')
    op.create_foreign_key(None, 'subs', 'employees', ['member_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'subs', 'projects', ['project_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subs', type_='foreignkey')
    op.drop_constraint(None, 'subs', type_='foreignkey')
    op.create_foreign_key(u'subs_ibfk_2', 'subs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(u'subs_ibfk_1', 'subs', 'employees', ['member_id'], ['id'])
    # ### end Alembic commands ###
